import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../app/Components/Navbar'
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Qcheck",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 left-0 z-50">
          <Navbar />
        </div>
        {children}

        <div>
          <Footer />
        </div>

      </body>
    </html>
  );
}
